name: Draggable Controls
urls:
  ckan_ver:  https://github.com/andrew-vant/dragctrl/releases/latest/download/DraggableNavball.version
  releases:  https://github.com/andrew-vant/dragctrl/releases
  changelog: https://raw.githubusercontent.com/andrew-vant/dragnav/master/CHANGES.md
ksp:
  version:     1.8.1
  version_min: 1.8.0
  version_max: 1.12.99
